version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/api"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      go-deps:
        patterns: ["*"]

  - package-ecosystem: "gomod"
    directory: "/agents/docker-agent"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      go-deps:
        patterns: ["*"]

  - package-ecosystem: "gomod"
    directory: "/agents/k8s-agent"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      go-deps:
        patterns: ["*"]

  - package-ecosystem: "gomod"
    directory: "/tests"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      go-deps:
        patterns: ["*"]

  - package-ecosystem: "npm"
    directory: "/ui"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      npm-deps:
        patterns: ["*"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      gha-deps:
        patterns: ["*"]
