# Auto-label PRs based on files changed

'component:ui':
  - changed-files:
    - any-glob-to-any-file: 'ui/**/*'

'component:backend':
  - changed-files:
    - any-glob-to-any-file: 'api/**/*'

'component:k8s-agent':
  - changed-files:
    - any-glob-to-any-file: 'agents/k8s-agent/**/*'

'component:docker-agent':
  - changed-files:
    - any-glob-to-any-file: 'agents/docker-agent/**/*'

'component:database':
  - changed-files:
    - any-glob-to-any-file: 'api/migrations/**/*'
    - any-glob-to-any-file: 'api/internal/db/**/*'

'documentation':
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.md'
      - 'docs/**/*'

'component:websocket':
  - changed-files:
    - any-glob-to-any-file: 'api/internal/websocket/**/*'

'component:vnc-proxy':
  - changed-files:
    - any-glob-to-any-file:
      - 'api/internal/websocket/vnc*.go'
      - 'agents/k8s-agent/pkg/vnc/**/*'

'testing':
  - changed-files:
    - any-glob-to-any-file:
      - '**/*_test.go'
      - '**/*.test.ts'
      - '**/*.test.tsx'
      - 'tests/**/*'

'component:plugin-system':
  - changed-files:
    - any-glob-to-any-file:
      - 'api/internal/plugins/**/*'
      - 'ui/src/plugins/**/*'
